In [ ]:
# Linear Regression
import pandas as pd
import numpy as np

In [30]:
data = {
  "Wind": [100, 50, 45, 60],
  "People": [2, 42, 31, 35],
  "Energy": [5, 25, 22, 18]
}

df = pd.DataFrame(data)

X = df[["Wind", "People"]]
X = X.to_numpy()
y = df["Energy"].to_numpy().reshape(-1, 1)
# X = np.array([[1], [2], [3], [4]])
# y = np.array([[2], [4], [6], [8]])
print("X=\n", X)
print("y=\n", y)

X=
 [[100   2]
 [ 50  42]
 [ 45  31]
 [ 60  35]]
y=
 [[ 5]
 [25]
 [22]
 [18]]


In [31]:
# By differentiating the matirx equation
# theta = (X^T * X)^-1 * X^T * y

X_mat = np.hstack([np.ones((X.shape[0], 1)), X])
print("X_mat=\n", X_mat)

theta = np.linalg.inv(X_mat.T.dot(X_mat)).dot(X_mat.T).dot(y)
print("theta=\n", theta)

# Predict
y_test = X_mat.dot(theta)
print(pd.DataFrame({"y_test": y_test.flatten(), "y": y.flatten()}))
print("MSE=", np.mean((y_test - y) ** 2))

X_mat=
 [[  1. 100.   2.]
 [  1.  50.  42.]
 [  1.  45.  31.]
 [  1.  60.  35.]]
theta=
 [[24.97615881]
 [-0.20751687]
 [ 0.20920152]]
      y_test   y
0   4.642875   5
1  23.386779  25
2  22.123147  22
3  19.847200  18
MSE= 1.5393330377813927


In [38]:
# By pytorch linear regression model with MSE loss
import torch

x_tensor = torch.from_numpy(X).float()
y_tensor = torch.from_numpy(y).float()

model = torch.nn.Linear(X.shape[1], y.shape[1])
criterion = torch.nn.MSELoss()
optimizer = torch.optim.SGD(model.parameters(), lr=0.0001)

for epoch in range(100):
 
    # Compute predictions by calling model
    pred_y = model(x_tensor)
 
    # Compute loss
    loss = criterion(pred_y, y_tensor)
 
    # Calculate gradients by running the backpropagation
    optimizer.zero_grad()
    loss.backward()

    # Update the model parameters
    optimizer.step()

    # Print the loss after every 10 epoch
    if epoch % 10 == 0:
        print('epoch {}, loss {}'.format(epoch, loss.item()))

print("Weight=\n", model.weight)
print("Bias=\n", model.bias)

# Predict
y_test = model(x_tensor).detach().numpy()
print(pd.DataFrame({"y_test": y_test.flatten(), "y": y.flatten()}))
print("MSE=", np.mean((y_test - y) ** 2))

epoch 0, loss 971.918701171875
epoch 10, loss 98.64098358154297
epoch 20, loss 18.554264068603516
epoch 30, loss 7.509305000305176
epoch 40, loss 5.985984802246094
epoch 50, loss 5.775803089141846
epoch 60, loss 5.746721267700195
epoch 70, loss 5.742613792419434
epoch 80, loss 5.741952896118164
epoch 90, loss 5.741762161254883
Weight=
 Parameter containing:
tensor([[0.0370, 0.5494]], requires_grad=True)
Bias=
 Parameter containing:
tensor([-0.1371], requires_grad=True)
      y_test   y
0   4.664368   5
1  24.789961  25
2  18.561186  22
3  21.314264  18
MSE= 5.741638964867036
